name: Spellcheck

# When this workflow triggers
on:
  push:
  workflow_dispatch:

# Job definition
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.35.0
      with:
        config_path: .spellcheck-config.yml